flowchart LR
  n_stonebranch_PROD_agent_machine01["agent: machine01"]
  n_stonebranch_PROD_calendar_BUSINESS_DAYS["calendar: BUSINESS_DAYS"]
  n_stonebranch_PROD_command_839f31339ca67757["command: 839f31339ca67757"]
  n_stonebranch_PROD_command_abe08ff03ed79b2a["command: abe08ff03ed79b2a"]
  n_stonebranch_PROD_credential_CRED_APP["credential: CRED_APP"]
  n_stonebranch_PROD_task_JOB_A["task: JOB_A"]
  n_stonebranch_PROD_task_JOB_B["task: JOB_B"]
  n_stonebranch_PROD_trigger_TRG_JOB_A["trigger: TRG_JOB_A"]
  n_stonebranch_PROD_variable_RUN_DATE["variable: RUN_DATE"]
  n_stonebranch_PROD_task_JOB_A -->|runs_on| n_stonebranch_PROD_agent_machine01
  n_stonebranch_PROD_task_JOB_A -->|uses_calendar| n_stonebranch_PROD_calendar_BUSINESS_DAYS
  n_stonebranch_PROD_task_JOB_A -->|uses_credential| n_stonebranch_PROD_credential_CRED_APP
  n_stonebranch_PROD_task_JOB_A -->|runs_command| n_stonebranch_PROD_command_839f31339ca67757
  n_stonebranch_PROD_task_JOB_A -->|uses_variable| n_stonebranch_PROD_variable_RUN_DATE
  n_stonebranch_PROD_task_JOB_B -->|depends_on_success| n_stonebranch_PROD_task_JOB_A
  n_stonebranch_PROD_task_JOB_B -->|runs_on| n_stonebranch_PROD_agent_machine01
  n_stonebranch_PROD_task_JOB_B -->|runs_command| n_stonebranch_PROD_command_abe08ff03ed79b2a
  n_stonebranch_PROD_trigger_TRG_JOB_A -->|starts| n_stonebranch_PROD_task_JOB_A
