flowchart LR
  n_stonebranch_PROD_task_JOB_A["task: JOB_A"]
  n_stonebranch_PROD_trigger_TRG_JOB_A["trigger: TRG_JOB_A"]
  n_stonebranch_PROD_trigger_TRG_JOB_A -->|starts| n_stonebranch_PROD_task_JOB_A
