flowchart LR
  n_stonebranch_PROD_task_JOB_A["task: JOB_A"]
  n_stonebranch_PROD_variable_RUN_DATE["variable: RUN_DATE"]
  n_stonebranch_PROD_task_JOB_A -->|uses_variable| n_stonebranch_PROD_variable_RUN_DATE
