/* offline HTML graph data. Generated by stonebranch-dependency-tool; do not hand-edit. */
window.GRAPH_DATA = {
  "edges": [
    {
      "category": "dependencies",
      "confidence": 0.97,
      "evidence_file": "workflows/WF_REPORTING.json",
      "evidence_key": "workflow_edge",
      "evidence_path": "$.workflowEdges[0]",
      "evidence_value": "build_report -> depends_on_success -> MON_ETL",
      "graph_edge_id": "1a6322e2f1236d4527d64f49",
      "id": "default:task:build_report|depends_on_success|default:task:mon_etl|1a6322e2f1236d4527d64f49",
      "native_relation": "workflow_edge",
      "relation": "depends_on_success",
      "source": "default:task:build_report",
      "target": "default:task:mon_etl"
    },
    {
      "category": "dependencies",
      "confidence": 0.97,
      "evidence_file": "workflows/WF_ARCHIVE.json",
      "evidence_key": "workflow_edge",
      "evidence_path": "$.workflowEdges[0]",
      "evidence_value": "copy_files -> depends_on_success -> MON_LOAD",
      "graph_edge_id": "bdcfa277f5dac2927e527f77",
      "id": "default:task:copy_files|depends_on_success|default:task:mon_load|bdcfa277f5dac2927e527f77",
      "native_relation": "workflow_edge",
      "relation": "depends_on_success",
      "source": "default:task:copy_files",
      "target": "default:task:mon_load"
    },
    {
      "category": "dependencies",
      "confidence": 0.95,
      "evidence_file": "tasks/JOB_B.json",
      "evidence_key": "predecessorTask",
      "evidence_path": "$.predecessorTask",
      "evidence_value": "JOB_A",
      "graph_edge_id": "a3165b9d8bc4e54833c0936d",
      "id": "default:task:job_b|depends_on_success|default:task:job_a|a3165b9d8bc4e54833c0936d",
      "native_relation": "references_predecessor",
      "relation": "depends_on_success",
      "source": "default:task:job_b",
      "target": "default:task:job_a"
    },
    {
      "category": "dependencies",
      "confidence": 0.97,
      "evidence_file": "workflows/WF_ETL.json",
      "evidence_key": "workflow_edge",
      "evidence_path": "$.workflowEdges[1]",
      "evidence_value": "load -> depends_on_success -> transform",
      "graph_edge_id": "a7287838a9868b47c83157b2",
      "id": "default:task:load|depends_on_success|default:task:transform|a7287838a9868b47c83157b2",
      "native_relation": "workflow_edge",
      "relation": "depends_on_success",
      "source": "default:task:load",
      "target": "default:task:transform"
    },
    {
      "category": "dependencies",
      "confidence": 0.97,
      "evidence_file": "workflows/WF_REPORTING.json",
      "evidence_key": "workflow_edge",
      "evidence_path": "$.workflowEdges[1]",
      "evidence_value": "publish -> depends_on_success -> build_report",
      "graph_edge_id": "c7e1d273c48380a9c9209caf",
      "id": "default:task:publish|depends_on_success|default:task:build_report|c7e1d273c48380a9c9209caf",
      "native_relation": "workflow_edge",
      "relation": "depends_on_success",
      "source": "default:task:publish",
      "target": "default:task:build_report"
    },
    {
      "category": "dependencies",
      "confidence": 0.97,
      "evidence_file": "workflows/WF_ETL.json",
      "evidence_key": "workflow_edge",
      "evidence_path": "$.workflowEdges[0]",
      "evidence_value": "transform -> depends_on_success -> extract",
      "graph_edge_id": "5e3e8bc50f149dc1034d1fe9",
      "id": "default:task:transform|depends_on_success|default:task:extract|5e3e8bc50f149dc1034d1fe9",
      "native_relation": "workflow_edge",
      "relation": "depends_on_success",
      "source": "default:task:transform",
      "target": "default:task:extract"
    }
  ],
  "groups": [
    {
      "child_count": 2,
      "graph_id": "stonebranch:default:workflow:WF_ARCHIVE",
      "id": "default:box:wf_archive",
      "key": "default:box:wf_archive",
      "kind": "workflow",
      "label": "WF_ARCHIVE",
      "name": "WF_ARCHIVE",
      "nested_container_count": 0,
      "parent": null,
      "source_file": "workflows/WF_ARCHIVE.json",
      "synthetic": false,
      "task_count": 2
    },
    {
      "child_count": 3,
      "graph_id": "stonebranch:default:workflow:WF_ETL",
      "id": "default:box:wf_etl",
      "key": "default:box:wf_etl",
      "kind": "workflow",
      "label": "WF_ETL",
      "name": "WF_ETL",
      "nested_container_count": 0,
      "parent": null,
      "source_file": "workflows/WF_ETL.json",
      "synthetic": false,
      "task_count": 3
    },
    {
      "child_count": 3,
      "graph_id": "stonebranch:default:workflow:WF_REPORTING",
      "id": "default:box:wf_reporting",
      "key": "default:box:wf_reporting",
      "kind": "workflow",
      "label": "WF_REPORTING",
      "name": "WF_REPORTING",
      "nested_container_count": 0,
      "parent": null,
      "source_file": "workflows/WF_REPORTING.json",
      "synthetic": false,
      "task_count": 3
    }
  ],
  "jobs": [
    {
      "canonical_key": "default:task:job_a",
      "depends_on": [],
      "graph_id": "stonebranch:default:task:JOB_A",
      "group": null,
      "id": "default:task:job_a",
      "key": "default:task:job_a",
      "kind": "task",
      "label": "JOB_A",
      "meta": {
        "attributes_hash": "ba9226d8b55872fb",
        "command_hash": "839f31339ca67757",
        "native_kind": "Universal Task",
        "semantic_command_hash": "b384ce2fa38d9bff"
      },
      "name": "JOB_A",
      "original_kind": "task",
      "source_file": "tasks/JOB_A.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:job_b",
      "depends_on": [
        "default:task:job_a"
      ],
      "graph_id": "stonebranch:default:task:JOB_B",
      "group": null,
      "id": "default:task:job_b",
      "key": "default:task:job_b",
      "kind": "task",
      "label": "JOB_B",
      "meta": {
        "attributes_hash": "467f34d562e4e038",
        "command_hash": "abe08ff03ed79b2a",
        "native_kind": "Universal Task",
        "semantic_command_hash": "61f843631f822874"
      },
      "name": "JOB_B",
      "original_kind": "task",
      "source_file": "tasks/JOB_B.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:copy_files",
      "depends_on": [
        "default:task:mon_load"
      ],
      "graph_id": "stonebranch:default:task:copy_files",
      "group": "default:box:wf_archive",
      "id": "default:task:copy_files",
      "key": "default:task:copy_files",
      "kind": "task",
      "label": "copy_files",
      "meta": {
        "attributes_hash": "8bee8832c58cb47e",
        "command_hash": "0886efee80b60d60",
        "native_kind": "Universal Task",
        "semantic_command_hash": "0c5ba50a1356e0ad"
      },
      "name": "copy_files",
      "original_kind": "task",
      "source_file": "tasks/copy_files.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:mon_load",
      "depends_on": [],
      "graph_id": "stonebranch:default:task:MON_LOAD",
      "group": "default:box:wf_archive",
      "id": "default:task:mon_load",
      "key": "default:task:mon_load",
      "kind": "task",
      "label": "MON_LOAD",
      "meta": {
        "attributes_hash": "e983eb2ea781aff5",
        "command_hash": null,
        "native_kind": "Task Monitor",
        "semantic_command_hash": null
      },
      "name": "MON_LOAD",
      "original_kind": "task",
      "source_file": "tasks/MON_LOAD.json",
      "synthetic": false,
      "watcher": true
    },
    {
      "canonical_key": "default:task:extract",
      "depends_on": [],
      "graph_id": "stonebranch:default:task:extract",
      "group": "default:box:wf_etl",
      "id": "default:task:extract",
      "key": "default:task:extract",
      "kind": "task",
      "label": "extract",
      "meta": {
        "attributes_hash": "3728985f33792a1f",
        "command_hash": "072ed08b4d48841e",
        "native_kind": "Universal Task",
        "semantic_command_hash": "1d013bdcf4afdf8a"
      },
      "name": "extract",
      "original_kind": "task",
      "source_file": "tasks/extract.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:load",
      "depends_on": [
        "default:task:transform"
      ],
      "graph_id": "stonebranch:default:task:load",
      "group": "default:box:wf_etl",
      "id": "default:task:load",
      "key": "default:task:load",
      "kind": "task",
      "label": "load",
      "meta": {
        "attributes_hash": "a50be7bec21a2f12",
        "command_hash": "ffc101b10fb21109",
        "native_kind": "Universal Task",
        "semantic_command_hash": "b0cbf364cc60f04a"
      },
      "name": "load",
      "original_kind": "task",
      "source_file": "tasks/load.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:transform",
      "depends_on": [
        "default:task:extract"
      ],
      "graph_id": "stonebranch:default:task:transform",
      "group": "default:box:wf_etl",
      "id": "default:task:transform",
      "key": "default:task:transform",
      "kind": "task",
      "label": "transform",
      "meta": {
        "attributes_hash": "aabec7b983701b53",
        "command_hash": "78beaa152e8dcac0",
        "native_kind": "Universal Task",
        "semantic_command_hash": "65a7165d8ab0f85f"
      },
      "name": "transform",
      "original_kind": "task",
      "source_file": "tasks/transform.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:build_report",
      "depends_on": [
        "default:task:mon_etl"
      ],
      "graph_id": "stonebranch:default:task:build_report",
      "group": "default:box:wf_reporting",
      "id": "default:task:build_report",
      "key": "default:task:build_report",
      "kind": "task",
      "label": "build_report",
      "meta": {
        "attributes_hash": "afa71f722dc071eb",
        "command_hash": "24fb195cc30be031",
        "native_kind": "Universal Task",
        "semantic_command_hash": "a07a9afad9abedf7"
      },
      "name": "build_report",
      "original_kind": "task",
      "source_file": "tasks/build_report.json",
      "synthetic": false,
      "watcher": false
    },
    {
      "canonical_key": "default:task:mon_etl",
      "depends_on": [],
      "graph_id": "stonebranch:default:task:MON_ETL",
      "group": "default:box:wf_reporting",
      "id": "default:task:mon_etl",
      "key": "default:task:mon_etl",
      "kind": "task",
      "label": "MON_ETL",
      "meta": {
        "attributes_hash": "38c51c74330e9ac0",
        "command_hash": null,
        "native_kind": "Task Monitor",
        "semantic_command_hash": null
      },
      "name": "MON_ETL",
      "original_kind": "task",
      "source_file": "tasks/MON_ETL.json",
      "synthetic": false,
      "watcher": true
    },
    {
      "canonical_key": "default:task:publish",
      "depends_on": [
        "default:task:build_report"
      ],
      "graph_id": "stonebranch:default:task:publish",
      "group": "default:box:wf_reporting",
      "id": "default:task:publish",
      "key": "default:task:publish",
      "kind": "task",
      "label": "publish",
      "meta": {
        "attributes_hash": "8f51de5c63405b90",
        "command_hash": "76241864a2f27f9b",
        "native_kind": "Universal Task",
        "semantic_command_hash": "b95a4a7669708b47"
      },
      "name": "publish",
      "original_kind": "task",
      "source_file": "tasks/publish.json",
      "synthetic": false,
      "watcher": false
    }
  ],
  "metadata": {
    "edges": 29,
    "env": "default",
    "groups": 3,
    "jobs": 10,
    "nodes": 26,
    "relation_categories": {
      "dependencies": 6
    },
    "source_system": "stonebranch",
    "warnings": 1
  },
  "schema_version": "1.0",
  "warnings": [
    "Created 8 synthetic nodes for unresolved references."
  ]
};
